### ISSUE TITLE
load nativescript-angular/application

### ISSUE THREAD

**Issue by sanathpathiraja** [NathanWalker/nativescript-ng2-translate#2]
import {nativeScriptBootstrap} from 'nativescript-angular/application';

but getting error,
Module build failed: Error: Cannot resolve module 'nativescript-angular/application'

**Comment by NathanWalker** [comment]
Are you trying to run the demo in this repo? Or did you install via npm? 

In either case, nativescript-angular must be installed.

**Comment by sanathpathiraja** [comment]
i installed via npm.
use,
npm install nativescript-ng2-translate --save and npm install nativescript-angular --save

**Comment by NathanWalker** [comment]
I would need more information here to help, for example your component setup and contents of your bootstrap file as well as your general project setup.

**Comment by NathanWalker** [comment]
If it's a github project you can share, I could help look there as well.

**Comment by sanathpathiraja** [comment]
yes ok.
