### ISSUE TITLE
Time to update to angular 2.00 ? 

### ISSUE THREAD

**Issue by developper89** [NathanWalker/nativescript-ng2-translate#4]
i'm heaving trouble installing the actual version on the last nativescript-angular release , they upgraded to ng2.0

**Comment by developper89** [comment]
problem solved

**Comment by Shamballa** [comment]
How did you fix it?
I got the error:
Error calling module function
Cannot compile ....../files/app/tns_modules/ng2-translate/ng-tranlate.js
SyntaxError: Unexpected token import File: ....../files/app/tns_modules/ng2-translate/ng-tranlate.js, line: 1, column: 60

imports: [
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (http: Http) => new TNSTranslateLoader('/public/i18n'),  
      deps: [Http] 
    })
]

**Comment by Shamballa** [comment]
Problem solved too
I used a newer version of ng2-translate (3.0.0). With the older version 2.4.4. it works!

**Comment by developper89** [comment]
Glad that you found it by yourself and sorry for answering now ..
